### ISSUE TITLE
near and far objects

### ISSUE THREAD

**Issue by shawnfromportland** [shawnfromportland/bermeoVR#6]
to keep a good dynamic visual depth, out of the window of the train there should be near, mid, and far objects to view.
examples of near objects: 
- telephone pole or radio antenna right alongside train tracks
- a tunnel asset that the train drives under simulating a tunnel through a mountain
- dense trees just a meter away from the train simulating forest conditions

mid-field objects:
- barn
- more trees. the more plants the better!
- farm house and garden plot (corn rows )
- cow
- broken bits of fence or railroad
- broken down car

distant-field objects:
- medium sized city skyline (this could almost be 2d if it was far enough in the distance, but maybe it could have slight 3d
- distant huge mountains (this will also be part of the skybox itself, but maybe there could be some distant 2D mountain sillhouettes that could receive shading)
- airplane in the sky
- clouds

-

**Comment by ToxSam** [comment]
I just wetransfered you some updates

Upgraded the detail of some of the stuff inside the train
Upgraded floor 
Upgraded door
upgraded Sofas
added "coffee"
added wall lamps to all places
added top lights

uploaded a small spoon for the coffee ,

**Comment by ToxSam** [comment]
Uploaded the Tunnel and phone Pole

I'm working on more near objects like a fence and trees now

**Comment by shawnfromportland** [comment]
You can commit meshes directly to the unity project, or I also made this shared google drive folder you should be able to upload to
https://drive.google.com/folderview?id=0BxeGQJyKyK1DdS1pQUhPQjRPLVE

**Comment by ToxSam** [comment]
I'm working on terrains now, this will improve the experience 100% sure, plus it might need some experimentation 

to help me out I'm gonna commit a small asset  that I use to export from Unity to Maya

**Comment by shawnfromportland** [comment]
i made some sketches the other day about how these terrain pieces can technically work, but I guess I'll just see what you come up with and we will talk after that 👍

**Comment by ToxSam** [comment]
Uploaded 4 tiles, the best way to make them is to overlap them a bit

still need fixing tho

https://gyazo.com/484f9c1781633a4e6ea0bbb8445af251

**Comment by ToxSam** [comment]
Here is a picture reference with the old ones on top
https://gyazo.com/53b4016e7c5bc89c6ef7c2179d36064c

**Comment by shawnfromportland** [comment]
@ToxSam see some of the terrain objects ideas above, see if there is anything you want to create. the fences are awesome.
